# PromptFlow Orchestrator (YAML is absolute hell)

main:
  params: [args]
  steps:
    - init:
        assign:
          - job_id: ${args.job_id}
          - project_id: "promptflow-project-xyz" 
          - database_id: "promptflow"
          - jobs_collection: "jobs"
          - results_collection: "results"
          
          # URLS
          - worker_url: "https://prompt-eval-worker-fr6bgye44q-uc.a.run.app"
          - generator_url: "https://us-central1-promptflow-project-xyz.cloudfunctions.net/prompt-generator"

    - log_start:
        call: sys.log
        args:
          text: '${"Starting Milestone 3 AI Loop for job_id: " + job_id}'

    - get_job_details:
        call: googleapis.firestore.v1.projects.databases.documents.get
        args:
          name: ${"projects/" + project_id + "/databases/" + database_id + "/documents/" + jobs_collection + "/" + job_id}
        result: job_document

    - decode_job_data:
        assign:
          - job_config: ${job_document.fields.config.mapValue.fields}
          - test_dataset: ${job_document.fields.testDataset.arrayValue.values}
          - base_prompt: ${job_config.basePrompt.stringValue}
          - eval_metric: ${job_config.evaluationMetric.stringValue}
          # Attempt to get parents. Default to null if missing.
          - raw_parents: ${map.get(job_config, "parentPrompts")}

    - set_status_running:
        call: googleapis.firestore.v1.projects.databases.documents.patch
        args:
          name: ${job_document.name}
          updateMask:
            fieldPaths: ["status"]
          body:
            fields:
              status:
                stringValue: "RUNNING"

    # GENERATE PROMPTS
    - generate_population:
        call: http.post
        args:
            url: ${generator_url}
            auth:
              type: OIDC
            body:
                base_prompt: ${base_prompt}
                # Pass the Firestore array structure directly to the generator
                parent_prompts_firestore: ${raw_parents}
                count: 4 
        result: gen_response

    - extract_prompts:
        assign:
            - candidate_prompts: ${gen_response.body.prompts}

    # EVALUATE POPULATION (Nested Loop)
    - evaluate_prompts:
        parallel:
            for:
                value: prompt_text
                in: ${candidate_prompts}
                steps:
                    - test_data_loop:
                        for:
                            value: test_item
                            in: ${test_dataset}
                            steps:
                                - run_one_test:
                                    call: http.post
                                    args:
                                        url: ${worker_url}
                                        auth:
                                          type: OIDC
                                        body:
                                            prompt: ${prompt_text}
                                            test_input: ${test_item.mapValue.fields.input.stringValue}
                                            eval_metric: ${eval_metric}
                                    result: eval_result

                                - save_result:
                                    call: googleapis.firestore.v1.projects.databases.documents.createDocument
                                    args:
                                        parent: ${"projects/" + project_id + "/databases/" + database_id + "/documents"}
                                        collectionId: ${results_collection}
                                        body:
                                            fields:
                                                jobId:
                                                  stringValue: ${job_id}
                                                prompt:
                                                  stringValue: ${prompt_text}
                                                output:
                                                  stringValue: ${eval_result.body.output}
                                                score:
                                                  doubleValue: ${eval_result.body.score}
                                                reasoning:
                                                  stringValue: ${default(map.get(eval_result.body, "reasoning"), "Reasoning Missing in Worker Response")}
                                                timestamp:
                                                  timestampValue: ${time.format(sys.now())}
                                    result: saved_doc

    - set_status_complete:
        call: googleapis.firestore.v1.projects.databases.documents.patch
        args:
          name: ${job_document.name}
          updateMask:
            fieldPaths: ["status"]
          body:
            fields:
              status:
                stringValue: "COMPLETE"
        
    - finish:
        return: "Job completed successfully."
