# PromptFlow: The "Real" Orchestrator (Milestone 2)
# This workflow reads a job from Firestore, runs all tests in parallel,
# and saves the results.

main:
  params: [args]
  steps:
    - init:
        assign:
          - job_id: ${args.job_id}
          - project_id: "promptflow-project-xyz"
          - database_id: "promptflow" # The DB name you chose
          - jobs_collection: "jobs"
          - results_collection: "results"
          # Make sure your worker URL is still correct here
          - worker_url: "https://prompt-eval-worker-fr6bgye44q-uc.a.run.app"

    - log_start:
        call: sys.log
        args:
          text: '${"Starting Milestone 2 workflow for job_id: " + job_id}'

    # Step 1: Read the job from Firestore
    - get_job_details:
        call: googleapis.firestore.v1.projects.databases.documents.get
        args:
          name: ${"projects/" + project_id + "/databases/" + database_id + "/documents/" + jobs_collection + "/" + job_id}
        result: job_document

    - decode_job_data:
        assign:
          - job_config: ${job_document.fields.config.mapValue.fields}
          - test_dataset: ${job_document.fields.testDataset.arrayValue.values}
          - base_prompt: ${job_config.basePrompt.stringValue}
          - eval_metric: ${job_config.evaluationMetric.stringValue}

    # Step 2: Update job status to "RUNNING"
    - set_status_running:
        call: googleapis.firestore.v1.projects.databases.documents.patch
        args:
          name: ${job_document.name}
          updateMask:
            fieldPaths:
              - "status"
          body:  # <-- FIX WAS HERE (was 'document:')
            fields:
              status:
                stringValue: "RUNNING"
        
    # Step 3: Run all evaluations in parallel
    - evaluate_population:
        parallel:
          for:
            value: test_item
            in: ${test_dataset}
            steps:
              - run_one_test:
                  call: http.post
                  args:
                    url: ${worker_url}
                    auth:
                      type: OIDC
                    body:
                      prompt: ${base_prompt}
                      test_input: ${test_item.mapValue.fields.input.stringValue}
                      eval_metric: ${eval_metric}
                  result: eval_result
              
              # Step 4: Save each result to the 'results' collection
             # Step 4: Save each result to the 'results' collection
              - save_result:
                  call: googleapis.firestore.v1.projects.databases.documents.createDocument
                  args:
                    parent: ${"projects/" + project_id + "/databases/" + database_id + "/documents"}
                    collectionId: ${results_collection}
                    body:  # <-- THIS IS THE FIX
                      fields:
                        jobId:
                          stringValue: ${job_id}
                        prompt:
                          stringValue: ${eval_result.body.prompt}
                        output:
                          stringValue: ${eval_result.body.output}
                        score:
                          doubleValue: ${eval_result.body.score}
                        timestamp:
                          timestampValue: ${time.format(sys.now())}
                  result: saved_doc 
                  
    # Step 5: Update job status to "COMPLETE"
    - set_status_complete:
        call: googleapis.firestore.v1.projects.databases.documents.patch
        args:
          name: ${job_document.name}
          updateMask:
            fieldPaths:
              - "status"
          body:  # <-- FIX WAS HERE (was 'document:')
            fields:
              status:
                stringValue: "COMPLETE"
        
    - finish:
        return: ${"Job " + job_id + " completed."}
